version: '2.1'
services:
  db:
    image: mariadb:10.2
    ports:
      - "9494:3306"
    volumes:
      - /etc/localtime:/etc/localtime
      - biometricdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      ohrmdevnet:
        ipv4_address: 10.4.1.102
    restart: always
    container_name: attendance_mariadb_102

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
    - /etc/localtime:/etc/localtime
    environment:
      PMA_HOSTS: db
    networks:
      ohrmdevnet:
        ipv4_address: 10.4.2.2
    restart: always
    container_name: attendance_phpmyadmin

volumes:
  biometricdata:

networks:
  ohrmdevnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.4.0.0/16
         gateway: 10.4.0.1