version: '2.1'
services:
  db102:
    image: orangehrm/orangehrm-db-images:mariadb-10.2
    expose:
      - "3306"
    volumes:
      - ./logs/mysql_logs/db102:/var/log
      - /etc/localtime:/etc/localtime
      - biometricdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.1.102
    restart: always
    container_name: dev_mariadb_102

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
    - /etc/localtime:/etc/localtime
    environment:
      PMA_HOSTS: db55,db102
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.2.2
    restart: always
    container_name: dev_phpmyadmin

volumes:
  biometricdata:

networks:
  ohrmdevnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1